### ISSUE TITLE
Readme.mdのインストール欄に「STUフォントが必要」って書いた方がいいかも

### ISSUE THREAD

**Issue by nano-nano** [miyax0227/myxQuizHex#1]
プログラム本体とは一切関係が無いですが...

鳥居くん製作のSTUフォントを入れないと、鳥居マークが「;」になっちゃいますね。
＃万人が使うものでも無いし、端折ってもいいのかも知れませんが。

**Comment by nano-nano** [comment]
フォント自体はfontディレクトリの中に入っている（```/font/STU XVIII.ttf```ですよね？）
HTML側からそれを参照するようにすれば良いはず？

**Comment by miyax0227** [comment]
STU XVIII.ttfへの参照は、下記のCSSファイルの@font-faceで行っているのですが、それが効いていないということになります。
https://github.com/miyax0227/myxQuizHex/blob/master/css/hex-long.css

原因は調査しますが、暫定措置はローカルシステムへのインストールの手順追加ですかね…

# 別のCSSで記載しているMigmixフォントへの参照はいかがでしょうか？

**Comment by miyax0227** [comment]
このコメント欄もmarkdownなんですね。一番下のコメントは強調したかったわけではなく、コメント的な意味合いの「#」です。

**Comment by nano-nano** [comment]
> このコメント欄もmarkdownなんですね。

そうなんですよー
Markdownが割と好きな私としてはありがたいのですが。

という話はさておいて。
ローカルでいじってたら何となく原因が分かってきたので、ちょろっと修正してプルリク出します。

**Comment by nano-nano** [comment]
> 別のCSSで記載しているMigmixフォントへの参照はいかがでしょうか？

こっちは参照が効いていそうです。:smiley::thumbsup:

**Comment by miyax0227** [comment]
Pull Requestをmasterに反映しました。
こちらのローカル環境で試験して解消したことを確認しましたのでクローズします。
ありがとうございました。
